### ISSUE TITLE
set cgroup.type value 

### ISSUE THREAD

**Issue by rllf** [libcgroup/libcgroup#131]
Dear all, in order to set the cgroup.type to ```threaded``` via C API,  I use this "workaround" 
       
```  
err = cgroup_add_value_string(cgroup_get_controller(cg_jd, "cpuset") ,"cgroup.type","threaded");
err = cgroup_modify_cgroup(cg_jd); 
``` 

because I can't find an interface as 
```
int cgroup_add_value_string (struct cgroup *cgroup,  const char *name,  const char *value)
```
that I expected to set the cgroup.type value. Did I misunderstand something?

thx for your support.

**Comment by kamalesh-babulal** [comment]
Hi @rllf,

**Comment by rllf** [comment]
Hi @kamalesh-babulal but the cgroup.type belongs not directly to controller values as cpsuset.cpus or cpu.stats; 
Therefore an interface handling like below, would perhaps be more intuitive or? what do you think?
```
struct cgroup *cg = cgroup_new_cgroup(cgroup);
err = cgroup_add_value_string( cg, "cgroup.type", "threaded");
err = cgroup_modify_cgroup(cg_jd); 
```

**Comment by drakenclimber** [comment]
I ran the following successfully against the HEAD of main.  It's not exactly what you asked for, @rllf, but it's close.  Does this meet your needs?

```
#include <libcgroup.h>

#define CGNAME          "foo"

/*
 * NOTE - prior to running this, I created the cgroup by hand
 */
int main(void)
{
        struct cgroup_controller *ctrl;
        struct cgroup *cg;
        int ret;

        ret = cgroup_init();
        if (ret) {
                fprintf(stderr, "cgroup_init() failed: %d\n", ret);
                return 1;
        }   
            
        cg = cgroup_new_cgroup(CGNAME);
        if(!cg) {
                fprintf(stderr, "cgroup_new_cgroup() failed\n");
                return 2;
        }   

        ctrl = cgroup_add_controller(cg, "cgroup");
        if (!ctrl) {
                fprintf(stderr, "cgroup_add_controller() failed\n");
                ret = 3;
                goto out;
        }   

        ret = cgroup_add_value_string(ctrl, "cgroup.type", "threaded");
        if (ret) {
                fprintf(stderr, "cgroup_add_value_string() failed: %d\n", ret);
                goto out;
        }   

        ret = cgroup_modify_cgroup(cg);
        if (ret) {
                fprintf(stderr, "cgroup_modify_cgroup() failed: %d\n", ret);
                goto out;
        }   

out:
        cgroup_free(&cg);
        return ret;
}
```

**Comment by drakenclimber** [comment]
I would support it if someone wanted to make @rllf's proposed interface:
```
int cgroup_add_value_string (struct cgroup *cgroup,  const char *name,  const char *value)
```

It may be easiest to leave the internals of libcgroup the same, i.e. create a "secret" controller named `cgroup` and operate on it.  One question for the above interface, do we allow other controllers, e.g. `cpuset` to also be managed via this API?

**Comment by drakenclimber** [comment]
And how does the above work with cgroup v1?

**Comment by drakenclimber** [comment]
> @drakenclimber I have to be careful with my "half knowledge" but when i look into the data structure, it is clearly oriented on cgroupv1 structure neverless also in this structure the file croup.type is stored as value under the controller[1] but this value is "independent" of the controller more a cgroup.value. And I am happy that it works but the data structure differs from the relation of values to resources (cpu, cpuset (in my case)) and values to groups;

You are definitely correct that the internal data structure closely aligns to the v1 hierarchy.  Libcgroup was started in ~2008, and thus predates cgroupv2 and even systemd.

When we restarted work on libcgroup a few years ago, one of our overarching goals at the time was to be surgical with our changes so as to reduce the risk of breaking cgroup v1.  At that time, libcgroup had no continuous integration, unit tests, functional tests, or code coverage numbers.  Now that we have better software engineering processes in place, I am more amenable open to more aggressive refactoring.

With that said, we still need to support cgroup v1, so making the internal data structures match cgroup v2 may be trading one set of problems for another.  But I don't really know... :)
