### ISSUE TITLE
configure script has "with_bindings = false"

### ISSUE THREAD

**Issue by jeffmacdonald** [libcgroup/libcgroup#133]
I'm downloading https://github.com/libcgroup/libcgroup/releases/download/v2.0/libcgroup-2.0.tar.gz to use in a project. 

In line 12526: of the "configure" script there is code like this:

```
else
  with_bindings = false
fi
```

The spaces between the equals and the variable cause bash to crash with `/tmp/libcgroup-2.0-tar/libcgroup-2.0/configure: line 12526: with_bindings: command not found`

I'm not sure where the source is for the configure script.

**Comment by kamalesh-babulal** [comment]
Hi @jeffmacdonald,
Thanks for reporting the issue.  I am trying to reproduce this on Ubuntu 20.04 and Fedora 34, but the bash does not crash. Can you please share more information on the os/environment? The release `2.0` is not supported, I will recommend using [2.0.1](https://github.com/libcgroup/libcgroup/releases/download/v2.0.1/libcgroup-2.0.1.tar.gz).  Checkout branch with tag `v2.0` or `v2.0.1` `git clone https://github.com/libcgroup/libcgroup.git;cd libcgroup;git checkout -b 2.0.1 v2.0.1` and `configure.ac` will have the source for the configure script.

**Comment by jeffmacdonald** [comment]
This is on Centos8.2. The reason we're using 2.0 is because in this case a Vendor has recommended that exact tgz and I haven't heard back from them yet. "with_bindings = false" will always fail on bash because of the spaces , regardless of platform. With your test, are you sure that block of code was executing?

**Comment by kamalesh-babulal** [comment]
I had missed it previously, my bad.  Removing the spaces from the assignment fixes it.  Do you want to send a patch for it?

**Comment by jeffmacdonald** [comment]
Sure, done here https://github.com/libcgroup/libcgroup/pull/134 Thanks!

**Comment by drakenclimber** [comment]
Thanks, @kamalesh-babulal and @jeffmacdonald.  Pushed to `release-2.0` in commit 4c4ada850f0e55314609f2f324c545cf7ea19a4c
