### ISSUE TITLE
what's the relation between this project with the one at sourceforge 

### ISSUE THREAD

**Issue by HuKeping** [libcgroup/libcgroup#15]
Hi,

Is there any relationship between this project and `https://git.code.sf.net/p/libcg/libcg` ?

**Comment by drakenclimber** [comment]
Yes.

libcgroup was started in 2008 or so, and it was initially hosted on SourceForge.  A couple years ago we moved it this repository on GitHub.  Shortly after that I stepped in to help maintain it and have been slowly adding cgroup v2 support to libcgroup.  Unfortunately I don't have write access to the old SourceForge source to mark it as deprecated and point users here.

**Comment by HuKeping** [comment]
Thanks!
