### ISSUE TITLE
child process's cgroup is different from parent process? 

### ISSUE THREAD

**Issue by yataosu** [libcgroup/libcgroup#20]

**Comment by drakenclimber** [comment]
Hi @yatao91, could you please provide more details?  What issue are you seeing?  Do you have a series of steps to reproduce the issue?

Thanks!

**Comment by yatao91** [comment]
Sorry for less details.

cgconfig.conf:
```
group high {
    cpuset {
        cpuset.cpus = "4,5";
        cpuset.mems = "0";
        cpuset.cpu_exclusive = "0";
        cpuset.mem_hardwall = "1";
    }
    cpu {
        cpu.cfs_period_us = "100000";
        cpu.cfs_quota_us = "60000";
    }
}
group normal {
    cpuset {
        cpuset.cpus = "4,5";
        cpuset.mems = "0";
        cpuset.cpu_exclusive = "0";
        cpuset.mem_hardwall = "1";
    }
    cpu {
        cpu.cfs_period_us = "100000";
        cpu.cfs_quota_us = "180000";
    }
}
```
cgrules.conf
```
*:A                     cpu,cpuset          high
*                       cpu,cpuset          normal
```

In my case, there is a application, contains a main process and 2 child process make by subprocess.Popen, main process's name is A. child process will be made about every 10 seconds, about running 2 seconds.

In my thought, process A will be moved to cgroup high by cgrulesengd, and process A's child process will be moved to cgroup high too. 
But, child process moved to cgroup normal by cgred. ( I thought child process always has same cgroup with parent process )

How this happens?

**Comment by Werkov** [comment]
Hello,
please note the explanation from `cgrules.conf (5)`

> First rule which matches the criteria will be executed.

So in the case of process A, it's expected to be in the `high` group. Assuming the children are a different program than A, then they're eventually expected in the `normal` cgroup. What are the children process names wrt A?

**Comment by yatao91** [comment]
> Hello,
> please note the explanation from `cgrules.conf (5)`
> 
> > First rule which matches the criteria will be executed.
> 
> So in the case of process A, it's expected to be in the `high` group. Assuming the children are a different program than A, then they're eventually expected in the `normal` cgroup. What are the children process names wrt A?

I understand this. 
> First rule which matches the criteria will be executed.

But, child process is a different program than A ?  I thought child process should follow parent, like child process should be in parent's cgroup. 
Yesterday, I read the source code then found cgrulesengd has logical for `fork`, but I haven't found any fork log, all is PROC_EVENT_EXEC log. 
source code:
```
case PROC_EVENT_FORK:
    ppid = ev->event_data.fork.parent_pid;
    cpid = ev->event_data.fork.child_pid;
    
    ret = cgre_is_unchanged_child(ppid);
    if (ret) {
	    if (cgre_store_unchanged_process(cpid, CGROUP_DAEMON_UNCHANGE_CHILDREN))
		    return 1;
    }
    
    /*
	    * If this process was forked while changing parent's cgroup,
	    * this process's cgroup also should be changed.
	    */
    if (!cgre_was_parent_changed_when_forking(ev))
	    return 0;
    pid = ev->event_data.fork.child_pid;
    break;
case PROC_EVENT_EXIT:
    cgre_remove_unchanged_process(ev->event_data.exit.process_pid);
    return 0;
case PROC_EVENT_EXEC:
    /*
	    * If the unchanged process, the daemon should not change the
	    * cgroup of the process.
	    */
    if (cgre_is_unchanged_process(ev->event_data.exec.process_pid))
	    return 0;
    pid = ev->event_data.exec.process_pid;
    break;
```

**Comment by Werkov** [comment]
> But, child process is a different program than A

So it ends up in the `normal` cgroup _after_ migration by cgrulesengd.

>  I thought child process should follow parent, like child process should be in parent's cgroup.

True, right after fork(2) it'll be in the parent's cgroup but in response to the fork/exec events it'll be migrated (by the daemon) eventually. Does that clarify?

**Comment by yatao91** [comment]
> > But, child process is a different program than A
> 
> So it ends up in the `normal` cgroup _after_ migration by cgrulesengd.
> 
> > I thought child process should follow parent, like child process should be in parent's cgroup.
> 
> True, right after fork(2) it'll be in the parent's cgroup but in response to the fork/exec events it'll be migrated (by the daemon) eventually. Does that clarify?

Thanks! 
But after fork / exec events child process be migrated in not parent process cgroup. Is that reasonable? 
Cgroup is designd for resource controlling. If parent and child process in same cgroup, is that more reasonable? 
> Just my own doubt.

**Comment by drakenclimber** [comment]
Thanks @Werkov for helping out!

@yatao91, we added a feature to libcgroup v.42.2 (the latest release) to do exactly what you are requesting.  Here's the commit https://github.com/libcgroup/libcgroup/commit/ae76f3a8c9c90ac05feb046714f4f6566b24cd3c

In your case, if you picked up the latest libcgroup (again 0.42.2 or greater), and updated your cgrules.conf as follows, you should see your expected behavior.

cgrules.conf
```
*:A                     cpu,cpuset          high
# The following rule tells libcgroup to ignore any processes
# in the "high" cgroup.  Thus any processes matching this rule
# will not be moved to another cgroup
*                       cpu,cpuset          high        ignore
*                       cpu,cpuset          normal
```

**Comment by yatao91** [comment]
> Thanks @Werkov for helping out!
> 
> @yatao91, we added a feature to libcgroup v.42.2 (the latest release) to do exactly what you are requesting. Here's the commit [ae76f3a](https://github.com/libcgroup/libcgroup/commit/ae76f3a8c9c90ac05feb046714f4f6566b24cd3c)
> 
> In your case, if you picked up the latest libcgroup (again 0.42.2 or greater), and updated your cgrules.conf as follows, you should see your expected behavior.
> 
> cgrules.conf
> 
> ```
> *:A                     cpu,cpuset          high
> # The following rule tells libcgroup to ignore any processes
> # in the "high" cgroup.  Thus any processes matching this rule
> # will not be moved to another cgroup
> *                       cpu,cpuset          high        ignore
> *                       cpu,cpuset          normal
> ```

Thanks for reply!
I will try this version for my demand.
