### ISSUE TITLE
cgconfigparser is not working as expected

### ISSUE THREAD

**Issue by bharani-viswas** [libcgroup/libcgroup#21]
OS : SLES 15 SP1
kernel : 4.12.14-197.45

consider the following group  :  `group memory_test{​​​​
memory {​​​​
memory.low = 1G;
memory.max = 24G;
}​​​​
}​​​​`
Only the first configuration line is being set and the rest of them are being neglected , the same is the status with other settings as well (io, cpu) (Tested on SLES15 SP2)

**Comment by Werkov** [comment]
Hello @bharani-viswas. Let me ask some clarification questions:
 * What libcgroup version do you use?
 * What cgroup hierarchy do you use (hybrid, unified)?
 * How do you check that a configured value has been set?

**Comment by bharani-viswas** [comment]
- built from master branch
- unified
- looking at interface file in /sys/fs/cgroup/<slice>/memory.max

**Comment by Werkov** [comment]
> * built from master branch
> * unified

I see. Let me Cc: @drakenclimber .

**Comment by drakenclimber** [comment]
Thanks for the question, @bharani-viswas.  Today is busy for me, but I will look into this issue this week.

**Comment by drakenclimber** [comment]
@bharani-viswas, I have a proposed fix out for review.  Could you please let me know if it addresses your issue?  I also have a [proposed fix ](https://github.com/drakenclimber/libcgroup-tests/commit/dbc286a127805a1d56389510fd130e21dc1519e8) for the unit tests to ensure this issue doesn't arise again.

Also, if you would like credit, please provide your name/email address and I will give you credit in the `Reported-by:` field.  e.g.
`Reported-by: Tom Hromatka <tom.hromatka@oracle.com>`

**Comment by bharani-viswas** [comment]
Thanks @drakenclimber  its fixed 👍 

Bharani viswas : bharani.viswas@gmail.com

**Comment by drakenclimber** [comment]
Merged.  See commit https://github.com/libcgroup/libcgroup/commit/c38fa7e9a901e43a225975baa1bf3302d18324d3

Thanks @bharani-viswas
