### ISSUE TITLE
Which apis can be used with cgroup v1 ?

### ISSUE THREAD

**Issue by h2cw2l** [libcgroup/libcgroup#217]

**Comment by kamalesh-babulal** [comment]
Hello,
All of the APIs are available for Cgroup V1, please let us know in case you find any issues while using them.
Thanks.

**Comment by h2cw2l** [comment]
> Hello @h2cw2l All of the APIs are available for Cgroup V1, please let us know in case you find any issues while using them. Thanks.

Thanks, it is ok.
