### ISSUE TITLE
Whether is a way to keep cgred's result from overriding by systemd ? 

### ISSUE THREAD

**Issue by yataosu** [libcgroup/libcgroup#22]
#### Expected Behavior
`Cgrulesengd` move high priority service's pids to specified cpu cgroup, like `/high` which has a cpu quota 70%;
low priority service's pids to cpu cgroup, like `/low` which has a cpu quota 30%. ( all service bind to one single cpu core )

As you can see, I want to split one cpu core resource to two parts, through `cpu.cfs_quota_us`. 
Like high priority services use up to 70% cpu time, low priority services use up to 30% cpu time.

#### Actual Behavior
Services which controlled by `systemd`.
First,  `cgrulesengd` move service's pid to specified; 
then, `systemd` will fresh service's cgroup in some time;
finally, service's pids cpu cgroup will be changed by `systemd`.

#### Question
Whether is a way to keep cgred's result from overriding by systemd when handle cpu controller? 

#### Ref
[README_systemd](https://github.com/libcgroup/libcgroup/blob/835b7841c5083fa72d46f6493b9617100516f993/README_systemd#L54-L65)

In README_systemd, there is a `DefaultControllers=` can control whether systemd  create control groups for services automatically. But this param was removed from `systemd`. 

#### Environment
systemd-v219
libcgroup-0.41-21

**Comment by Werkov** [comment]
Hello @yataosu.

Please refer to the current systemd [documentation](https://systemd.io/CGROUP_DELEGATION/), namely the rule about single-writer. **cgred conficts with systemd on cpu hierarchy.** That renders cgred almost incompatible.

> Whether is a way to keep cgred's result from overriding by systemd when handle cpu controller?

The possible way I can think of is creating an auxiliary service with

    Slice=-.slice
    Delegate=cpu

And spawn the processes you want to classify with cgred from this unit. The you can use cgred rules to move in the cpu hieararchy in the service's _subtree_. (Not tested, just a theoretical idea to answer the question.)

Generally, I'd discourage using cgred if you are on a system where services are managed by systemd and just use the primitives as described in `systemd.resource-control (5)`.

**Comment by bharani-viswas** [comment]
From the given [documentation](https://systemd.io/CGROUP_DELEGATION/) we see that "don’t create your own cgroups below the root cgroup"
does that mean we should not create a slice in /sys/fs/cgroup  if we are to use the cgred  and not step into systemd's toes?

**Comment by Werkov** [comment]
@bharani-viswas That is right. Don't do that. (You may get away with own v1 cgroups for controllers _not_ [used by systemd](https://github.com/systemd/systemd/blob/2b767e9222809103cb756e368f0d71e906623bca/src/basic/cgroup-util.h#L19).)

**Comment by Apurva1995** [comment]
Thank you @Werkov 
I have a follow up question for V2, what is the ideal place to create a slice so that systemd doesn't interfere?

**Comment by yataosu** [comment]
@Werkov Thanks. I will try it.

**Comment by Apurva1995** [comment]
@Werkov 
Can you confirm that for all the controllers that are used by systemd in V2, we should not use cgred to classify processes for those controllers?
If so, then in what context cgred is useful now? Can it only be used for controllers not used by Systemd?
And since the root cgroup is controlled by systemd, where should we mount the cgroup that we want to control via cgred to follow Single writer rule?

**Comment by Werkov** [comment]
This seems to diverge a bit. The original question is related to v1 controllers (and hierarchies). I'd suggest filing a separate issue for better readability for possible v2 followups.

The approach with delegation and restricting cgred to the delegated subtree only should also work for v2 setup. (Again, I'd discourage using cgred together with systemd though, especially if you go forward with v2.)

Unless you run systemd with pure unified setup, it mounts v1 hierarchies for all the controllers found in `/proc/controllers`, no need to mount those.
Perhaps you meant with your question, what cgroup (subtree) you have available for cgred operations? Then it's the cgroup path of a unit that has `Delegate=` enabled. Does that clarify?

**Comment by drakenclimber** [comment]
This issue has been inactive for several months.  I'm closing it, but feel free to comment or reopen if there is new activity.
