### ISSUE TITLE
Messy versioning

### ISSUE THREAD

**Issue by kloczek** [libcgroup/libcgroup#223]
https://github.com/libcgroup/libcgroup/releases/tag/v3.0 there are tar balls with 3.0.0 version

**Comment by drakenclimber** [comment]
@kloczek, you are 100% correct.  libcgroup has a long (and strange) history of how it does its versions, and I tried to balance that history with our transition to github.  It's quite possible that in making this compromise, I made no one happy :(.

Here's the longer version:
* libcgroup has traditionally released new version, say X.Y.  When minor changes were made to the version, the release became X.Y.Z.  (This is readily apparent in the [old sourceforge site](https://sourceforge.net/projects/libcg/files/libcgroup/).)
* If you look at the source code of an X.Y version, you'll see that the library version is A.X.Y.  So for release 0.41, the library version is 1.0.41.  Argh
* When we transitioned to github, I wanted to keep the library version in sync with the release version
* We have users that rely on the X.Y.Z library version format.  I am uncertain if there are users that rely on the X.Y (and occasional X.Y.Z) format of the *.tar file
* Speculation here, but it appears that the early release *.tar files were built by hand.  We have switched to using `make dist` which obviously autogenerates the version numbers based on configure.ac

So (perhaps foolishly) I decided to name the release 3.0 in deference to old libcgroup conventions.  Due to our use of continuous integration and more automated tooling, the *.tar I uploaded was versioned 3.0.0.  I considered renaming the *.tar file but that felt wrong to me.

Let me know if this causes issues for you.  I would like to release a 3.0.1 release this fall.  We have some more features (hopefully simple systemd integration) that we would like to get out.

**Comment by drakenclimber** [comment]
And of course the 3.0.1 release version numbers will be fully consistent :)

**Comment by kloczek** [comment]
Just in case adding leading `v` is not any problem because it is dropped automatically by hithubb on generate tar ball from tag 😋 
Nevertheless .. thank you for the understanding 😄 
Just please keep versioning consistent because it iw very importand to be abke use that fo any automations 😄 

If may I ask .. when will be ET of 3.0.1 release? 🤔 

BTW: st it woud be any problem to add `v3.0.0` tag on top of existing `v3.0`? 🤔

**Comment by drakenclimber** [comment]
> Just please keep versioning consistent because it iw very importand to be abke use that fo any automations smile

Definitely.  I'm fearful that no matter what I did I would have broken someone's automation

> If may I ask .. when will be ET of 3.0.1 release? thinking

I don't have a set date, but I would like to get systemd support out this fall.  My hope is in the next couple months

> BTW: st it woud be any problem to add `v3.0.0` tag on top of existing `v3.0`? thinking

[Done](https://github.com/libcgroup/libcgroup/tree/v3.0.0)

Thanks for the comments on how this broke your automation.  I'm hoping to (slowly) transition away from the libcgroup/sourceforge paradigm and get onto a more standard github delivery scheme.

Let me know if there's anything else you need

**Comment by kloczek** [comment]
Thank you very much 👍 😄 
Closing,

**Comment by kloczek** [comment]
Just tested autogenerated from git tar ball as source input and looks like it is not possible to use that as such resource.
All because tests/ content is from other repo.
Is it any reanon why tests/ are not in the same repo?
```console
+ cd libcgroup-3.0.0
+ autoreconf -fiv
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: aclocal --force -I m4
autoreconf: running: /usr/bin/autoconf --force
configure.ac:33: warning: The macro `AC_CONFIG_HEADER' is obsolete.
configure.ac:33: You should run autoupdate.
./lib/autoconf/status.m4:719: AC_CONFIG_HEADER is expanded from...
configure.ac:33: the top level
configure.ac:159: warning: AC_PROG_LEX without either yywrap or noyywrap is obsolete
./lib/autoconf/programs.m4:716: _AC_PROG_LEX is expanded from...
./lib/autoconf/programs.m4:709: AC_PROG_LEX is expanded from...
aclocal.m4:765: AM_PROG_LEX is expanded from...
configure.ac:159: the top level
configure.ac:167: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:167: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:167: the top level
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:29: installing 'build-aux/ar-lib'
configure.ac:29: installing 'build-aux/compile'
configure.ac:30: installing 'build-aux/config.guess'
configure.ac:30: installing 'build-aux/config.sub'
configure.ac:17: installing 'build-aux/install-sh'
configure.ac:17: installing 'build-aux/missing'
configure.ac:230: error: required file 'tests/Makefile.in' not found
configure.ac:230: error: required file 'tests/ftests/Makefile.in' not found
configure.ac:230: error: required file 'tests/gunit/Makefile.in' not found
samples/c/Makefile.am:23: warning: variable 'empty_cgroup_v2_SOURCES' is defined but no program or
samples/c/Makefile.am:23: library has 'empty_cgroup_v2' as canonical name (possible typo)
samples/c/Makefile.am:17: warning: variable 'get_all_controller_SOURCES' is defined but no program or
samples/c/Makefile.am:17: library has 'get_all_controller' as canonical name (possible typo)
samples/c/Makefile.am:14: warning: variable 'get_controller_SOURCES' is defined but no program or
samples/c/Makefile.am:14: library has 'get_controller' as canonical name (possible typo)
samples/c/Makefile.am:15: warning: variable 'get_mount_point_SOURCES' is defined but no program or
samples/c/Makefile.am:15: library has 'get_mount_point' as canonical name (possible typo)
samples/c/Makefile.am:20: warning: variable 'get_procs_SOURCES' is defined but no program or
samples/c/Makefile.am:20: library has 'get_procs' as canonical name (possible typo)
samples/c/Makefile.am:18: warning: variable 'get_variable_names_SOURCES' is defined but no program or
samples/c/Makefile.am:18: library has 'get_variable_names' as canonical name (possible typo)
samples/c/Makefile.am:22: warning: variable 'logger_SOURCES' is defined but no program or
samples/c/Makefile.am:22: library has 'logger' as canonical name (possible typo)
samples/c/Makefile.am:16: warning: variable 'proctest_SOURCES' is defined but no program or
samples/c/Makefile.am:16: library has 'proctest' as canonical name (possible typo)
samples/c/Makefile.am:12: warning: variable 'read_stats_SOURCES' is defined but no program or
samples/c/Makefile.am:12: library has 'read_stats' as canonical name (possible typo)
samples/c/Makefile.am:10: warning: variable 'setuid_SOURCES' is defined but no program or
samples/c/Makefile.am:10: library has 'setuid' as canonical name (possible typo)
samples/c/Makefile.am:19: warning: variable 'test_named_hierarchy_SOURCES' is defined but no program or
samples/c/Makefile.am:19: library has 'test_named_hierarchy' as canonical name (possible typo)
samples/c/Makefile.am:13: warning: variable 'walk_task_SOURCES' is defined but no program or
samples/c/Makefile.am:13: library has 'walk_task' as canonical name (possible typo)
samples/c/Makefile.am:11: warning: variable 'walk_test_SOURCES' is defined but no program or
samples/c/Makefile.am:11: library has 'walk_test' as canonical name (possible typo)
samples/c/Makefile.am:21: warning: variable 'wrapper_test_SOURCES' is defined but no program or
samples/c/Makefile.am:21: library has 'wrapper_test' as canonical name (possible typo)
src/Makefile.am: installing 'build-aux/depcomp'
configure.ac: installing 'build-aux/ylwrap'
autoreconf: error: automake failed with exit status: 1
```
Probably it woud be goot to execure autoupdate->review the changes->commit updates.

**Comment by drakenclimber** [comment]
> Just tested autogenerated from git tar ball as source input and looks like it is not possible to use that as such resource. All because tests/ content is from other repo. Is it any reanon why tests/ are not in the same repo?

@giani had requested this a few years ago.  @giani, thoughts?

> Probably it woud be goot to execure autoupdate->review the changes->commit updates.

Good idea
