### ISSUE TITLE
BUG: libcgroup fails without /proc/cgroups even when it's not necessary

### ISSUE THREAD

**Issue by 0n-s** [libcgroup/libcgroup#234]
libcgroup (or at least `pam_cgroup`) fails to initialize when `/proc/cgroups` isn't present, even on a cgroup2-only system where "/proc/cgroups is meaningless" (https://docs.kernel.org/admin-guide/cgroup-v2.html#deprecated-v1-core-features).

This can cause libcgroup to fail on mainline Linux today if procfs is mounted with `subset=pid`, which is, as you might expect, a version of procfs with just the files relating to processes & none of the other top-level stuff.

(tested with libcgroup v2.0 & libcgroup ed283eab173addd3b5c2dd666de8f3086125e106)

**Comment by kamalesh-babulal** [comment]
@0n-s Thanks for reporting the issue.  The `cgroup_init()` will fail when `/procs` is mounted with `subset=pid`. 
```
Reproducer:
# cgget -g cpu:user.slice 
user.slice:
cpu.weight: 100
cpu.stat: usage_usec 36538181
        user_usec 26650585
        system_usec 9887595
        core_sched.force_idle_usec 0
        nr_periods 0
        nr_throttled 0
        throttled_usec 0
        nr_bursts 0
        burst_usec 0
cpu.weight.nice: 0
cpu.pressure: some avg10=0.05 avg60=0.13 avg300=0.04 total=287782
        full avg10=0.00 avg60=0.00 avg300=0.00 total=138114
cpu.idle: 0
cpu.max.burst: 0
cpu.max: max 100000

# mount -o remount,subset=pid -t proc proc /proc
# cgget -g cpu:user.slice 
Error: cannot open /proc/cgroups: No such file or directory
cgget: libcgroup initialization failed: No such file or directory
```
I will fix this issue of dependency on `/proc/cgroups` alone to find the available controllers and post the patch sooner.
