### ISSUE TITLE
subtree +memory block cgroup_attach_task_pid

### ISSUE THREAD

**Issue by calvin2021y** [libcgroup/libcgroup#271]
Hi, thanks for the great work.

I am use libcgroup on ubuntu 22.10, catch this problem:

if I call  `+memory` first then I can not make cgroup_attach_task_pid work:

```sh
cgroup/src/api.c:1837] cannot write tid 505206 to /sys/fs/cgroup/test/cgroup.procs:Resource busy
```

if I call cgroup_attach_task_pid first then I can not write `+memory` into `cgroup.subtree_control`:

```sh
/sys/fs/cgroup/test/cgroup.subtree_control -95, operation not supported on socket from 260
+memory errno 50016, Operation not supported
```

Is there a way to made this work to move myself into the new created cgroup, and keep the  `+memory` into `cgroup.subtree_control` ?

**Comment by Werkov** [comment]
[No](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html?highlight=v2#no-internal-process-constraint).

**Comment by calvin2021y** [comment]
OK.  I know this is not doable.

I try with this lib 3.0,  try create a init cgroup from pid 1 (as uid=0) in a root container with uid map.

cgroup_create_cgroup return this error:
```sh
[2:~/src/cgroup/src/api.c:201] fts_read failed
[2:~/src/cgroup/src/api.c:201] fts_read failed
[2:~/src/cgroup/src/api.c:201] fts_read failed
errno ECGOTHER
io error -95 operation not supported on socket from 173
```
any idea what cause this ECGOTHER ?  I check the root cgroup is create with 777 and owner is correct.

then try move pid 1 into this cgroup, get this error:
```sh
[2:~/src/cgroup/src/api.c:1702] invalid /sys/fs/cgroup/init/cgroup.type: domain invalid
```

Is this relate to fist ECGOTHER error ?  how to make the cgroup_attach_task_pid work for this case ? (container root as pid 1, create new group and move self into it,  there is only one process in this step)
