### ISSUE TITLE
Created coordination between self-hosted runners

### ISSUE THREAD

**Issue by kamalesh-babulal** [libcgroup/libcgroup#295]
Currently, there are three self-hosted runners on each VM, there is a chance of
runners stomping over each other.  We need better coordination. One idea is using
`ACTIONS_RUNNER_HOOK_JOB_STARTED` or `ACTIONS_RUNNER_HOOK_JOB_COMPLETED`
to `systemctl stop <other runner service>` and `systemctl start <other runner service>`
creating a mutual exclusion.  Its not bulletproof but might work

**Comment by drakenclimber** [comment]
Resolve in pull request #310
