### ISSUE TITLE
cpu.weight value is not written when cgroup has 'cpu' enabled in cgroup.subtree_control

### ISSUE THREAD

**Issue by justinfx** [libcgroup/libcgroup#323]
I've been working through this for a few hours and I cannot tell if this is a bug or some kind of under-documented rule.

## Goal

I want to modify the value of 'cpu.weight' from the default 100 to a value, such as 8

## What I have tried

**The following does not work**

1. Construct a new cgroup, under the root (for simplicity), such as "my_group"
2. Add controller 'cpu'
3. Create the cgroup on disk
4. Load cgroup object back (ie we have loaded a previously created cgroup)
5. Set the value of "cpu.weight" to 8
6. Modify the cgroup to commit the value. Notice that the value of "my_group/cpu.weight" on disk remains 100

**The following does work**

1. Construct a new cgroup, under the root (for simplicity), such as "my_group2"
2. Add controller 'cpu'
3. Set the value of "cpu.weight" to 8
4. Create the cgroup on disk
5. Notice that the value of "my_group2/cpu.weight" is set to 8

## Observations

It seems libcgroup does not actually manage to set "cpu.weight" if the 'cpu' controller is already enabled in the "cgroup.subtree_control", even though debug logging implies it is trying to set the correct value. This does not seem to be a limit of cgroup v2 from the kernel, as I can manually write a value from the shell and see it reflected in all cases.

**Comment by drakenclimber** [comment]
Here's a python script that should do what you want @justinfx.

There does seem to be some fragility in how the Python bindings interact with the libcgroup C code.  The C code has an implicit set of steps that it expects the user to follow.  But in Python, there's a lot more flexibility, and it's easy to do the steps in the "wrong" order.  If/When you encounter issues like this, let us know.  I really want to improve the Python APIs.

Anyway, here's one way to do what you want:
```#!/usr/bin/env python3
from libcgroup import Cgroup, Version

cg = Cgroup('my_group', Version.CGROUP_V2)
cg.add_controller('cpu')
cg.create()
cg.get()
for setting_key in cg.controllers['cpu'].settings.keys():
    if setting_key == 'cpu.weight':
        print('cg\'s {} = {}'.format(setting_key,
              cg.controllers['cpu'].settings[setting_key]))

cg2 = Cgroup('my_group', Version.CGROUP_V2)
cg2.add_controller('cpu')
cg2.add_setting('cpu.weight', '99')
cg2.cgxset()

cg3 = Cgroup('my_group', Version.CGROUP_V2)
cg3.add_controller('cpu')
cg3.get()
for setting_key in cg3.controllers['cpu'].settings.keys():
    if setting_key == 'cpu.weight':
        print('cg3\'s {} = {}'.format(setting_key,
              cg3.controllers['cpu'].settings[setting_key]))
```

```
$ sudo PYTHONPATH="PATH_TO_THE_PY_SO" ./write-weight.py
cg's cpu.weight = 100
cg3's cpu.weight = 99
```

You likely don't need to create 3 instances of the Cgroup class, but it made the example a little simpler/easier.

**Comment by drakenclimber** [comment]
I think the steps you outlined in your "does not work" section likely break unwritten assumptions in the C code.  If you're comfortable sharing, please share the relevant python code.  I'm guessing that the python is violating these assumptions in the C code.  I'd love to try and clear some of these up if possible.

Thanks.

**Comment by justinfx** [comment]
Thanks for the sample code, @kamalesh-babulal  and @drakenclimber !

The reason I only initially listed bullet points as a repro is that I maintain my own python cgroup bindings, internally in my company. They are pretty thin calls into libcgroup where possible. 

@kamalesh-babulal your C code is *almost* what I am doing through my python bindings. Here is a modified version that illustrates the exact calls (note the free and reload of the cgroup):

```C
#include <stdlib.h>
#include <libcgroup.h>

#define CGRP_NAME       "my_group2"
#define CTRL_NAME       "cpu"
#define CTRL_SETTING    "cpu.weight"
#define PROC_CPU_WEIGHT "/sys/fs/cgroup/my_group2/cpu.weight"

int print_cpu_weight()
{
        FILE *fp;
        char value[10];

        fp = fopen(PROC_CPU_WEIGHT, "r");
        if (!fp) {
                fprintf(stderr, "Failed to open %s\n", PROC_CPU_WEIGHT);
                return 1;
        }

        fgets(value, 10, fp);
        fprintf(stderr, "cpu.weight %s", value);
        fclose(fp);

        return 0;
}

int main(void)
{
        struct cgroup_controller *cgc;
        struct cgroup *cgroup;
        int ret;

        ret = cgroup_init();
        if (ret) {
                fprintf(stderr, "cgroup initialization failed\n");
                exit (1);
        }

        /*
         * Create
         */
        cgroup = cgroup_new_cgroup(CGRP_NAME);
        if (!cgroup) {
                fprintf(stderr, "Failed to allocate cgroup %s\n", CGRP_NAME);
                exit(1);
        }

        cgc = cgroup_add_controller(cgroup, CTRL_NAME);
        if (!cgc) {
                fprintf(stderr, "Failed to add controller %s\n", CTRL_NAME);
                exit (1);
        }

        ret = cgroup_create_cgroup(cgroup, 0);
        if (ret) {
                fprintf(stderr, "Failed to create cgroup %s\n", CGRP_NAME);
                goto out;
        }

        ret = print_cpu_weight();
        if (ret)
                goto out;

        cgroup_free(&cgroup);

        /*
         * Load and modify
         */
        cgroup = cgroup_new_cgroup(CGRP_NAME);
        if (!cgroup) {
                fprintf(stderr, "Failed to allocate cgroup %s\n", CGRP_NAME);
                exit(1);
        }

        ret = cgroup_get_cgroup(cgroup);
        if (ret) {
                fprintf(stderr, "Failed to get cgroup %s\n", CGRP_NAME);
                goto out;
        }

        cgc = NULL;
        cgc = cgroup_get_controller(cgroup, CTRL_NAME);
        if (!cgc) {
                fprintf(stderr, "Failed to get controller %s\n", CTRL_NAME);
                exit (1);
        }

        ret = cgroup_set_value_string(cgc, CTRL_SETTING, "8");
        if (ret) {
                fprintf(stderr, "Failed to set the %s value\n", CTRL_SETTING);
                goto out;
        }

        ret = cgroup_modify_cgroup(cgroup);
        if (ret) {
                fprintf(stderr, "Failed to modify cgroup\n");\
                goto out;
        }

        ret = print_cpu_weight();
        if (ret)
                goto out;

out:
        cgroup_free(&cgroup);
        return 0;
}
```

@drakenclimber you are right that my python bindings are likely violating assumptions in the C code. The issue I see is that I have never actually used the `group_add_*` API. I only ever call i nto `cgroup_set_*`. And I had never noticed the difference until I had revisited the bindings this last month to update them to libcgroup 3.x. I see how your python code goes through the "add" variant of the api. To be honest, if you are looking for feedback on the API, I was pretty confused as to the difference between the two and as to why there is even two types of value setters. If I can properly understand the nature of when to use one vs the other, I can refactor my python bindings to do the right thing under the hood. I only currently expose a public "Controller.set_value" in python.

**Comment by justinfx** [comment]
This docstring is likely what led me to structure my code, thinking I could "load -> set -> modify":

```c
/**
 * Physically modify a control group in kernel. All parameters added by
 * cgroup_add_value_ or cgroup_set_value_ are written.
 * Currently it's not possible to change and owner of a group.
 *
 * @param cgroup
 */
int cgroup_modify_cgroup(struct cgroup *cgroup);
``` 

The docstring says all params are written, regardless of whether "add" or "set" was used. 

I ended up reading the source code for `cgroup_cgxset` to try and understand why it was a better option proposed in the python approach. From what I am reading, it uses a "convert" to a new cgroup data structure, and then a "modify" to commit the parameters. Is that a kind of workaround to ensure the correct order of operations?

**Comment by drakenclimber** [comment]
> Thanks for the sample code, @kamalesh-babulal and @drakenclimber !
> 
> The reason I only initially listed bullet points as a repro is that I maintain my own python cgroup bindings, internally in my company. They are pretty thin calls into libcgroup where possible.

No worries and no need to share your company's code.

> @drakenclimber you are right that my python bindings are likely violating assumptions in the C code. The issue I see is that I have never actually used the `cgroup_add_value_*` API. I only ever call into `cgroup_set_value_*`. And I had never noticed the difference until I had revisited the bindings this last month to update them to libcgroup 3.x. I see how your python code goes through the "add" variant of the api. To be honest, if you are looking for feedback on the API, I was pretty confused as to the difference between the two and as to why there is even two types of value setters. If I can properly understand the nature of when to use one vs the other, I can refactor my python bindings to do the right thing under the hood. I only currently expose a public "Controller.set_value" in python.

This is one area where I need to improve.  The python bindings are still a work in progress.

Sorry in advance for the length, but I'm going to give you a brief History of the Libcgroup Python World Volume 1:
* Initially libcgroup had swig Python bindings that directly mapped to the C APIs
* A few years back, I started adding python bindings as 1-to-1 wrappers around the C code.  This was primarily done to aid in automated testing and ensure C APIs were behaving properly
* Somewhere along the way of this testing, it became apparent that the Python API had a lot of potential and I started thinking about making it a legit interface for users

So now we're in that weird teenage phase where the Python API is growing up, but it's not quite there yet.  Some APIs aren't really pythonic, like you said see `add()` vs `set()`, and are simply a rehash of the C APIs.

I would like to release libcgroup v3.0.1 in the next month or two.  (The Python API would be released as part of this, but I will definitely tag it as in-development and subject to change.)  Then for v3.0.2, I would like to focus on making the Python API more sane, pythonic, and user friendly.

Keep the comments like this coming, please.  They'll definitely help us to make the API more sane.  Thanks!

**Comment by justinfx** [comment]
> I'm guessing that the legacy C APIs had a preferred methodology like you cited ...
> Initially libcgroup had swig Python bindings that directly mapped to the C APIs

I appreciate the info! This legacy C API is when I first wrote my Cython bindings, and then I didn't follow the large refactors to the C api until recently.

> So now we're in that weird teenage phase where the Python API is growing up, but it's not quite there yet. Some APIs aren't really pythonic, like you said see add() vs set(), and are simply a rehash of the C APIs.

In my case the python library isn't even the issue. So it is the C api add vs set that still confuses me. Would you be able to offer a quick description of the difference in when to use one vs the other? I'm wondering if I can just abstract away the call to "add", given the right calling conditions. Or if the caller clearly needs to know when "add" vs "set" is required.

**Comment by drakenclimber** [comment]
> In my case the python library isn't even the issue. So it is the C api add vs set that still confuses me. Would you be able to offer a quick description of the difference in when to use one vs the other? I'm wondering if I can just abstract away the call to "add", given the right calling conditions. Or if the caller clearly needs to know when "add" vs "set" is required.

Sure, I can do that.  It might be a day or two before I can get to it, but I should be able to put it together by the end of the week.  Thanks!

**Comment by kamalesh-babulal** [comment]
Apologies, that could not participate in the discussion and I am yet to go through the discussion. Wanted to update a
finding on why `cpu.weight` doesn't write the value `8`, using the sample test code:

....
   - cgroup_new_cgroup()
   - cgroup_get_cgroup()
   - cgroup_get_controller()
     This call will read all the cpu controller settings of the cgroup `my_group2`, which includes `cpu.weight`, as well as
     `cpu.weight.nice`, along with other settings.
     Why is `cpu.weight.nice` import to this discussion?
     `cpu.weight.nice` and `cpu.weight` both are alternative interfaces that can be used to change the weight of the cgroup. Hence writing a value in one of the interfaces will parallelly change the value of the other to the closest approximation.
   - cgroup_set_value_string(cgc, "cpu.weight", "8);
   - cgroup_modify_cgroup(cgroup)
       This will write all of the cpu controller read from the `cgroup_get_controller()`, with a modified `cpu.weight` setting.
     - cg_set_control_value() - `/sys/fs/cgroup//my_group2/cpu.weight` and value = 8 (called first)
       This sets the value of `cpu.weight` to `8` and `cpu.weight.nice` is set to 11 (closet approximation).
     - cg_set_control_value() - `/sys/fs/cgroup//my_group2/cpu.weight.nice` and value = 0 (called second)
       This call undo the previous write and `cpu.weight` is set `100` when the nice value is set 0, the value 0 is the default
       value, that gets assigned. 

with the following delta over @justinfx  code, should fix the issue:
```
diff --git a/test.c b/test.c
index 787a976..e2e2023 100644
--- a/test.c
+++ b/test.c
@@ -3,7 +3,8 @@
 
 #define CGRP_NAME       "my_group2"
 #define CTRL_NAME       "cpu"
-#define CTRL_SETTING    "cpu.weight"
+#define CTRL1_SETTING    "cpu.weight"
+#define CTRL2_SETTING    "cpu.weight.nice"
 #define PROC_CPU_WEIGHT "/sys/fs/cgroup/my_group2/cpu.weight"
 
 int print_cpu_weight()
@@ -85,12 +86,17 @@ int main(void)
                exit (1);
        }
 
-       ret = cgroup_set_value_string(cgc, CTRL_SETTING, "8");
+       ret = cgroup_set_value_string(cgc, CTRL1_SETTING, "8");
        if (ret) {
-               fprintf(stderr, "Failed to set the %s value\n", CTRL_SETTING);
+               fprintf(stderr, "Failed to set the %s value\n", CTRL1_SETTING);
                goto out;
        }
 
+       ret = cgroup_set_value_string(cgc, CTRL2_SETTING, "11");
+       if (ret) {
+               fprintf(stderr, "Failed to set the %s value\n", CTRL2_SETTING);
+               goto out;
+       }
        ret = cgroup_modify_cgroup(cgroup);
        if (ret) {
                fprintf(stderr, "Failed to modify cgroup\n");
```

alternatively, writing into `cpu.weight.nice` only can achieve the same result.  Another argument, is whether it is guaranteed that `cpu.weight` is always read/written before `cpu.weight.nice`? not sure about it for now. But seems to be the case, with several runs.

**Comment by kamalesh-babulal** [comment]
One approach would be to skip writing the non-dirty (non-modified) controller setting.
```
diff --git a/src/api.c b/src/api.c
index ad08bd3..e58b152 100644
--- a/src/api.c
+++ b/src/api.c
@@ -2296,6 +2296,27 @@ STATIC int cgroup_set_values_recursive(const char * const base,
        char *path = NULL;
 
        for (j = 0; j < controller->index; j++) {
+               /*
+                * ignore_non_dirty_failures is set while writing into
+                * existing cgroup to modify controller settings and
+                * unset during cgroup creation.  The subtle difference
+                * is that dirty flag is unset for all the controller
+                * settings during cgroup creation, whereas some or all
+                * controller settings have the dirty flag set during
+                * modification.
+                *
+                * Be careful with ignore_non_dirty flag, it's serves
+                * dual purpose:
+                * 1. Skip's writing of non-modified controller setting
+                *    since, the last read from the disk is set called
+                *    from cgroup_modify_cgroup() .
+                * 2. Reports the error while writing controller settings
+                *    to the disk if unset, called from
+                *    _cgroup_create_cgroup().
+                */
+               if (ignore_non_dirty_failures && controller->values[j]->dirty == false)
+                      continue;
+
                ret = asprintf(&path, "%s%s", base, controller->values[j]->name);
                if (ret < 0) {
                        last_errno = errno;
```
