### ISSUE TITLE
BUG: cgset can't handle `=` in the value

### ISSUE THREAD

**Issue by drakenclimber** [libcgroup/libcgroup#33]
See this [comment](https://github.com/libcgroup/libcgroup/issues/12#issuecomment-810431419) in Issue #12.

A user was setting io.max as follows, but the command fails due to the `=` character in the value.
`cgset -r io.max="8:16 wbps=1024" foo`

**Comment by drakenclimber** [comment]
Two additional comments for you @santiagorr

- You're welcome to fix this if you wish.  If not, I should be able to get to it in the next week or two.
- If you want credit for reporting the bug, please populate the following
  `Reported-by: Your Real Name <youremailaddress@arealemail.com>`

**Comment by drakenclimber** [comment]
And, of course, thanks for the help!

**Comment by santiagorr** [comment]
Thanks for confirming it's bug!

> Two additional comments for you @santiagorr
> 
>     * You're welcome to fix this if you wish.  If not, I should be able to get to it in the next week or two.

I think I will be short of cycles to handle this, especially after some recent covid-related government decisions. Please, go ahead if cannot provide anything.

>     * If you want credit for reporting the bug, please populate the following
>       `Reported-by: Your Real Name <youremailaddress@arealemail.com>`
Please use this:
`Reported-by: Santiago Ruano Rincón <santiago.ruano-rincon@imt-atlantique.fr>`

**Comment by drakenclimber** [comment]
Thanks, @santiagorr.  I have issued pull request #35 which should resolve this issue.
