### ISSUE TITLE
cgroup_get_current_controller_path() fails on cgroup v2

### ISSUE THREAD

**Issue by adriaan42** [libcgroup/libcgroup#335]
On cgroup2, the `/proc/<pid>/cgroup` files look like this:

```sh
$ cat /proc/$$/cgroup
0::/user.slice/user-1000.slice/session-1080.scope
```

Basically, on v2 the "controllers" field is empty, and the `fscanf` in https://github.com/libcgroup/libcgroup/blob/main/src/api.c#L4848 does not accept that as input. The call fails in a rather unfortunate way, returning `ECGOTHER` and "Success", because there is no `errno` set.

**Comment by kamalesh-babulal** [comment]
@adriaan42 Thanks for reporting the issue, the  `cgroup_get_current_controller_path()` needs to be fixed to support empty cgroups on cgroup v2.

**Comment by adriaan42** [comment]
@kamalesh-babulal I believe this is not only about empty cgroups, but it's a general v2 issue, where the "controllers" field in the file is always empty (and the first field is always `0`, cf. https://man7.org/linux/man-pages/man7/cgroups.7.html).
So on v2 it might not even make sense to have the `controller` argument.

**Comment by kamalesh-babulal** [comment]
@adriaan42 Agreed, the format of cgroup v2 controller has to be interpreted differently in comparison to cgroup v1.  The system can also be booted into the hybrid mode with some supported controller mounted as cgroup v2, by passing the `cgroup_no_v1` parameter to the kernel command line.  Can you please try the patches from #337  , they apply on the main branch.  May I add you to the `Reported-by` tag in the commit? if you are okay, could you share your preferred email id, so that I can add it to the tag?

**Comment by adriaan42** [comment]
@kamalesh-babulal thanks so much for the quick response!

> Can you please try the patches from #337 , they apply on the main branch.

I've just tried the current patches (v2 of your PR), and they work for me as expected.

> May I add you to the `Reported-by` tag in the commit? if you are okay, could you share your preferred email id, so that I can add it to the tag?

Sure. `Reported-by: Adriaan Schmidt <adriaan.schmidt@siemens.com>`

**Comment by kamalesh-babulal** [comment]
> I've just tried the current patches (v2 of your PR), and they work for me as expected.

@adriaan42 Thanks for testing the patch set.

> Sure. Reported-by: Adriaan Schmidt <adriaan.schmidt@siemens.com>

Thank you.

**Comment by drakenclimber** [comment]
Pushed to the main branch in commit 72ccaa389e874e70111f4a56330538441573c4e8.  Thanks @adriaan42 and @kamalesh-babulal
