### ISSUE TITLE
Problems in `cgroupv2_subtree_control_recursive()`

### ISSUE THREAD

**Issue by adriaan42** [libcgroup/libcgroup#351]
I believe that the adding of controllers in `cgroupv2_subtree_control_recursive()` starts one level too deep:

- I try to create a cgroup and add a controller, e.g.
  ```c
  struct cgroup *cg = cgroup_new_cgroup("a/b/c");
  cgroup_add_controller(cg, "cpu");
  cgroup_create_cgroup(cg, 1);
  ```
- This will fail if the "root" subtree_control file `/sys/fs/cgroup/cgroup.subtree_control` does not contain `cpu`. After putting it there manually, the above code works.
- Using strace I can see that the recursive execution starts to touch `subtree_control` files beginning with `/sys/fs/cgroup/a/cgroup.subtree_control`

Also, I think that the function is broken when called with `enable=false`. In this case the recursion to remove a controller from the subtree_control files should be done in reverse. However, that case seems to never occur in the code, as the only call to `cgroupv2_subtree_control_recursive()` has `enable=true`.

**Comment by kamalesh-babulal** [comment]
@adriaan42 Thank you for the report with a reproducer.  I am missing something with disabling cpu controller in `root` `subtree_control`, could please provide more information on the setup.

**Comment by drakenclimber** [comment]
> This will fail if the "root" subtree_control file `/sys/fs/cgroup/cgroup.subtree_control` does not contain `cpu`. After putting it there manually, the above code works.

Out of curiosity, how are you removing `cpu` from the root's `cgroup.subtree_control` file?  Are you doing this at boot time? 

```
$ sudo su -c "echo -cpu > /sys/fs/cgroup/cgroup.subtree_control"
bash: line 1: echo: write error: Device or resource busy
```

**Comment by adriaan42** [comment]
On my test system (arm64, built with Yocto and booting with systemd) the situation right after boot is:

```sh
# cat /sys/fs/cgroup/cgroup.controllers 
cpuset cpu io memory hugetlb pids
# cat /sys/fs/cgroup/cgroup.subtree_control 
memory pids
# mkdir /sys/fs/cgroup/a
# cat /sys/fs/cgroup/a/cgroup.controllers 
memory pids
# echo +cpu > /sys/fs/cgroup/a/cgroup.subtree_control 
sh: write error: No such file or directory
# echo +cpu > /sys/fs/cgroup/cgroup.subtree_control 
# cat /sys/fs/cgroup/a/cgroup.controllers 
cpu memory pids
# echo +cpu > /sys/fs/cgroup/a/cgroup.subtree_control 
```

So to enable the `cpu` controller on my cgroup I need to write to the subtree_control files in the hierarchy up to (but not including) my new cgroup. In my case, that last command writing `+cpu` to `/sys/fs/cgroup/a/cgroup.subtree_control` is not even necessary, and would only have an effect on cgroups created below `a/`.

**Comment by drakenclimber** [comment]
This is going to be a tricky issue to solve in libcgroup itself.

Due to the no-processes-in-an-inner-node rule, once a system has booted, it's often not possible to change the `cgroup.subtree_control` file in the root cgroup.  And to further compound the issue, systemd is the single-writer for the root cgroup and the first level of children.  (It doesn't always enforce the single-writer rule against the first level of children, but I am nervous to step on its toes in the root cgroup.)

What if you enable `DefaultCPUAccounting` in your systemd `system.conf` file?  Then the `cpu` controller should be enabled at boot time, and we can avoid some really ugly corner cases.

**Comment by adriaan42** [comment]
@drakenclimber Thanks for the explanations. After reading a bit more I agree that libcgroup should not touch `/sys/fs/cgroup/cgroup.subtree_control`, and I should use systemd mechanisms instead.

Unfortunately, `DefaultCPUAccounting` on kernels >4.15 does not require or enable the `cpu` controller: <https://github.com/systemd/systemd/blob/40fb9eebbc075ce1e63100386d2c5f177ad7d738/man/systemd-system.conf.xml#L448>.

However, I can use the `Delegate` property, which I should use anyways to play nice with systemd. This will enable the controller, and even disable it if no longer in use:
```sh
# cat /sys/fs/cgroup/cgroup.subtree_control 
memory pids
# systemd-run -P --property=Delegate=cpu cat /sys/fs/cgroup/cgroup.subtree_control
Running as unit: run-u9.service
cpu memory pids
# cat /sys/fs/cgroup/cgroup.subtree_control 
memory pids
```
