### ISSUE TITLE
cgroup_get_procs should take const char * not char *

### ISSUE THREAD

**Issue by dandedrick** [libcgroup/libcgroup#445]
cgroup_get_procs does not modify name or controller but it takes them in as `char *` and not `const char *`.  Taking these in as non-const creates issues for clients. To start with consider the following example snippet:
```
cgroup_get_procs(name, "memory", &pids, &size);
```
This will print out the following warning since controller is not const:
```
cgroup-test.cpp:10:28: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   10 |     cgroup_get_procs(name, "memory", &pids, &size);
```

Next using with c++ strings it causes additional issues. Consider this code snippet:
```
std::string name("cgroup-name");
cgroup_get_procs(name.c_str(), "memory", &pids, &size);
```
This will get the following error:
```
cgroup-test.cpp:11:32: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
   11 |     cgroup_get_procs(name.c_str(), "memory", &pids, &size);
      |                      ~~~~~~~~~~^~
      |                                |
      |                                const char*
```

The `cg_build_path` function that this calls into already takes `const char *` and that's the only place these variables are used.

**Comment by kamalesh-babulal** [comment]
@dandedrick Thanks for the report. Can I add your name and email in `Reported-by:` tag? If yes, can you share your email id?

**Comment by dandedrick** [comment]
Sure. dan.dedrick at gmail dot com. Thanks.
