### ISSUE TITLE
No such commit 918443b in libcgroup-tests

### ISSUE THREAD

**Issue by hicqu** [libcgroup/libcgroup#58]
I'm trying to make a Rust binding for this repo. However I meet an error when fetching this repo with `git` in `cargo`:
```
Caused by:
  object not found - no match for id (918443bd89efb807d92c1754b0b3fbff4bd3304f); class=Odb (9); code=NotFound (-3)
```
Seems the commit `918443b` can not' be found.

Then I clone `libcgroup-tests` and I confirm that `918443b` is not a valid commit for `libcgroup-tests`.

However, If I run this:
```
$ git clone https://github.com/libcgroup/libcgroup
$ git submodule update --init --recursive
```
I can found that `918443b` is checked-out for `tests`!

It really confuses me. Could you help me?

**Comment by Werkov** [comment]
Interesting, the object isn't reachable in the tests repo but Github likely [keeps it](https://github.community/t/does-github-ever-purge-commits-or-files-that-were-visible-at-some-time/1944/2) through the ping from the submodule.
You can work it around with

    libcgroup-tests (main) > git fetch origin 918443bd89efb807d92c1754b0b3fbff4bd3304f

But the ultimate fix is up to @drakenclimber to push the reference into the tests repo or update the module reference.

**Comment by drakenclimber** [comment]
Thanks for the bug report @hicqu.  And thanks for the help @Werkov.

I have tagged commit [918443bd89ef](https://github.com/libcgroup/libcgroup-tests/commit/918443bd89efb807d92c1754b0b3fbff4bd3304f) in libcgroup-tests.  Here's the tag - [lost-commit-918443bd89ef](https://github.com/libcgroup/libcgroup-tests/releases/tag/lost-commit-918443bd89ef).

Let me know if you are still having issues with that commit, and I'll dig in deeper.  Thanks!

**Comment by drakenclimber** [comment]
@hicqu Please comment or reopen this issue if the above fix doesn't work for you.
