### ISSUE TITLE
Fails to build with musl

### ISSUE THREAD

**Issue by rossburton** [libcgroup/libcgroup#61]
musl doesn't provide `fts.h`[1]  so libcgroup doesn't compile with musl. However, there is a standalone implementation of fts for musl users[2] which can be used.

If configure.ac called `AC_SEARCH_LIBS([fts_open], [fts], [], [AC_MSG_ERROR(...)])` then it would check for `fts_open` in the standard C library, and if it wasn't present check in `libfts`.

[1] https://wiki.musl-libc.org/faq.html
[2] https://github.com/void-linux/musl-fts

**Comment by giani** [comment]
@rossburton we don't officially support anything other than glibc. This doesn't mean that we will actively work against other libc implementations, but that we cannot test against them. If you are willing to provide a patch, test and ensure there are no regressions against glibc, we are happy to accept them.
