### ISSUE TITLE
BUG: unused shared libraries installed?

### ISSUE THREAD

**Issue by santiagorr** [libcgroup/libcgroup#62]
Hi there,

libcgroup installs files of two shared libraries: libcgroupfortesting and libcgset that I think are unused (correct me please if I am wrong). libcgroup shouldn't avoid installing those?

Cheers,

 -- S

**Comment by drakenclimber** [comment]
Thanks, @santiagorr.  You are correct; those two libraries are for testing only.  Good find.

**Comment by rossburton** [comment]
Wouldn't it be more idiomatic to use `noinst_lib_LTLIBRARIES = libcgset.la`?

**Comment by rossburton** [comment]
https://github.com/libcgroup/libcgroup/pull/70
