### ISSUE TITLE
BUG: cgroup.threads not supported

### ISSUE THREAD

**Issue by bjne** [libcgroup/libcgroup#64]
libcgroup has incorrect support for cgroup2 threads in cgroup_attach_task, where the documentation says
pid = tid, attaching a thread to a cgroup2 group actually adds the thread to cgroup.procs, which causes all
threads of the process to be added

**Comment by drakenclimber** [comment]
Good find, @bjne.  Thanks.  I've added it to my todo list for v2.0.1
