### ISSUE TITLE
tests submodule points to broken SHA

### ISSUE THREAD

**Issue by rossburton** [libcgroup/libcgroup#71]
The `tests` submodule on `main` points to 918443bd89efb807d92c1754b0b3fbff4bd3304f, which is a broken commit on libcgroup-tests as it has this change:

```
-TESTS = 001-cgget-basic_cgget_v1.py \
-       002-cgdelete-recursive_delete.py \
-       003-cgget-basic_cgget_v2.py
+TESTS = ftests.py -l 10 -L ftests.log
```

`TESTS` is treated as a list of scripts by automake, so it ends up calling `rm -L.log`.

I guess the submodule reference should be bumped to the HEAD of libcgroup-tests?

**Comment by drakenclimber** [comment]
Thanks, @rossburton.  I tried hacking around with some more automated ways to keep the tests submodule up to date but couldn't find an easily-automatable way to do it.  Anyway the ref is updated for now :)
